### ISSUE TITLE
No `requirements.txt` file

### ISSUE THREAD

**Issue by AlexanderPershin** [enablebanking/OpenBankingPythonExamples#2]
I've just tried to run this repo code locally and got errors. I guess that's because I installed missing packages with pip directly and didn't consider versions. Could you add `requirements.txt`?

**Comment by botsman** [comment]
The only package which is not in the standard library is `enablebanking`.  
It is not open source, so the `requirements.txt` will not help.  
You can download sample of our enablebanking SDK from here: https://enablebanking.com/core/ (scroll to the bottom, there is a "Test with one sandbox connector" text, where you can order some bank to test.
After that sample is installed you can try to run the script again

**Comment by AlexanderPershin** [comment]
Got it. As I understand additionally I need to ask for developer license in order to run this example, because there are missing keys and project crashes when I'm trying to run it

**Comment by botsman** [comment]
I assume you mean settings for the downloaded connector?
For that you don't need license, just settings.

In general for most banks users are free to register in the bank's developer portal and create an application there.
You can tell me which connector/bank you've downloaded, I will be able to point you where to obtain those

**Comment by AlexanderPershin** [comment]
I created app for Nordea

**Comment by botsman** [comment]
Then you can register here https://developer.nordeaopenbanking.com/
Create a sandbox app https://developer.nordeaopenbanking.com/apps
Obtain that app's clientId and clientSecret and put those settings in the script in this repo: 

The settings should look something like:
```
{
  "sandbox": True,
  "consentId": None,
  "accessToken": None,
  "refreshToken": None,
  "redirectUri": "https://your-redirect-url.com",
  "country": "FI",
  "language": "en",
  "clientId": "<clientId>",
  "clientSecret": "<clientSecret>",
  "signKeyPath": "path/to/key.pem"
}
```

Also, don't forget to get a private key from Nordea dev portal. After you've downloaded it, you need to put its path to `signKeyPath` parameter.
It can be found here:
https://developer.nordeaopenbanking.com/documentation?api=Access%20Authorization%20API
search by "You have to define also eidasPrivateKey env variable. Sandbox private key for static eIDAS certicate is:"

So the key file should look something like:
```
-----BEGIN PRIVATE KEY-----
<content_of_the_key_here>
-----END PRIVATE KEY-----

```

**Comment by AlexanderPershin** [comment]
Thank you

**Comment by AlexanderPershin** [comment]
Nope, still getting an error:
```
Traceback (most recent call last):
  File "/media/alexander/Multimedia/dev/lab/honkio/enablebanking/OpenBankingPythonExamples/aisp_example.py", line 164, in <module>
    main()
  File "/media/alexander/Multimedia/dev/lab/honkio/enablebanking/OpenBankingPythonExamples/aisp_example.py", line 58, in main
    api_meta = get_connector_meta(
  File "/media/alexander/Multimedia/dev/lab/honkio/enablebanking/OpenBankingPythonExamples/aisp_example.py", line 50, in get_connector_meta
    meta_api = enablebanking.MetaApi(enablebanking.ApiClient())
  File "/media/alexander/Multimedia/dev/lab/honkio/enablebanking/OpenBankingPythonExamples/venv/lib/python3.9/site-packages/enablebanking/api_client.py", line 29, in __init__
    if C is _A or isinstance(C,str):from enablebanking import eb_core as B
ImportError: cannot import name 'eb_core' from 'enablebanking' (/media/alexander/Multimedia/dev/lab/honkio/enablebanking/OpenBankingPythonExamples/venv/lib/python3.9/site-packages/enablebanking/__init__.py)
Exception ignored in: <function ApiClient.__del__ at 0x7f4edde229d0>
Traceback (most recent call last):
  File "/media/alexander/Multimedia/dev/lab/honkio/enablebanking/OpenBankingPythonExamples/venv/lib/python3.9/site-packages/enablebanking/api_client.py", line 43, in __del__
    def __del__(A):A.pool.close();A.pool.join()
AttributeError: 'ApiClient' object has no attribute 'pool'
```

**Comment by botsman** [comment]
Oh, true.
Our SDK was updated to use asyncronous python a while ago.
So it looks like our example is outdated. I will try to update it soon

**Comment by botsman** [comment]
I've updated our examples. Please check if it works for you

**Comment by AlexanderPershin** [comment]
Hello,
Strange but it didn't change anything, same error:
```
Traceback (most recent call last):
  File "/media/alexander/Multimedia/dev/lab/honkio/enablebanking/OpenBankingPythonExamples/aisp_example.py", line 159, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/media/alexander/Multimedia/dev/lab/honkio/enablebanking/OpenBankingPythonExamples/aisp_example.py", line 52, in main
    api_meta = await get_connector_meta(
  File "/media/alexander/Multimedia/dev/lab/honkio/enablebanking/OpenBankingPythonExamples/aisp_example.py", line 44, in get_connector_meta
    meta_api = enablebanking.MetaApi(enablebanking.ApiClient())
  File "/media/alexander/Multimedia/dev/lab/honkio/enablebanking/OpenBankingPythonExamples/venv/lib/python3.9/site-packages/enablebanking/api_client.py", line 29, in __init__
    if C is _A or isinstance(C,str):from enablebanking import eb_core as B
ImportError: cannot import name 'eb_core' from 'enablebanking' (/media/alexander/Multimedia/dev/lab/honkio/enablebanking/OpenBankingPythonExamples/venv/lib/python3.9/site-packages/enablebanking/__init__.py)
Exception ignored in: <function ApiClient.__del__ at 0x7ff92547f8b0>
Traceback (most recent call last):
  File "/media/alexander/Multimedia/dev/lab/honkio/enablebanking/OpenBankingPythonExamples/venv/lib/python3.9/site-packages/enablebanking/api_client.py", line 43, in __del__
AttributeError: 'ApiClient' object has no attribute 'pool'

```

**Comment by botsman** [comment]
Would you be able to try to run in with python 3.10 or 3.11?

**Comment by botsman** [comment]
I guess it was my bad updating the Python examples :)
We have both sync and async version of our SDK for python, and the error related to the `loop` made me think that it is due to the fact the we provide async version of our SDK as an example.
However, I've double checked and it seems that we provide sync version to be downloaded as an example.
I am still not sure what causes this `loop` error though.

Could you please try to run following example? 

```
import datetime
import logging
import readline  # imported to allow pasting long lines into `input` function
import time
from typing import Dict, Any
import uuid

import enablebanking

logging.getLogger().setLevel(logging.INFO)

REDIRECT_URL = "https://enablebanking.com/auth_redirect"  # PUT YOUR REDIRECT URI HERE


CONNECTOR_NAME = "Nordea"
CONNECTOR_COUNTRY = "FI"
CONNECTOR_SETTINGS = {
    "sandbox": True,
    "consentId": None,
    "accessToken": None,
    "redirectUri": REDIRECT_URL,
    "country": "DK",
    "language": None,
    "clientId": "<YOUR CLIENT ID>",
    "clientSecret": "<YOUR CLIENT SECRET>",
    "signKeyPath": "/path/to/your/private.key",
}


def read_redirected_url(url, redirect_url):
    print("Please, open this page in browser: " + url)
    print("Login, authenticate and copy paste back the URL where you got redirected.")
    print(f"URL: (starts with %s): " % redirect_url)

    redirected_url = input()  # insert your url
    return redirected_url


def get_connector_meta(
    connector_name: str, connector_country: str
) -> enablebanking.MetaApi:
    meta_api = enablebanking.MetaApi(enablebanking.ApiClient())
    for conn in meta_api.get_connectors(country=connector_country).connectors:
        if conn.name == connector_name:
            return conn
    raise Exception("Meta not found")


def main():
    api_meta = get_connector_meta(
        CONNECTOR_NAME, CONNECTOR_COUNTRY
    )  # get meta information for current connector

    api_client = enablebanking.ApiClient(
        CONNECTOR_NAME, connector_settings=CONNECTOR_SETTINGS
    )  # Create client instance.

    auth_api = enablebanking.AuthApi(api_client)  # Create authentication interface.

    client_info = enablebanking.ClientInfo()
    connector_psu_headers = api_meta.required_psu_headers
    if "psuIpAddress" in connector_psu_headers:
        client_info.psu_ip_address = "10.10.10.10"

    if "psuUserAgent" in connector_psu_headers:
        client_info.psu_user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15"

    auth_api.set_client_info(client_info=client_info)

    access = enablebanking.Access(
        valid_until=(datetime.datetime.now() + datetime.timedelta(days=89))
    )
    get_auth_params: Dict[str, Any] = {"state": str(uuid.uuid4())}
    if api_meta.auth_info[0].info.access:
        get_auth_params["access"] = access
    auth_response = auth_api.get_auth(**get_auth_params)

    make_token_response = None
    if auth_response.url:
        # if url is returned, then we are doing redirect flow
        redirected_url = read_redirected_url(auth_response.url, REDIRECT_URL)
        query_params = auth_api.parse_redirect_url(redirected_url)
        logging.info("Parsed query: %s", query_params)
        make_token_response = auth_api.make_token(
            "authorization_code",  # grant type, MUST be set to "authorization_code"
            code=query_params.code,
            auth_env=auth_response.env,
        )
    else:
        # decoupled flow otherwise
        # Doing a retry to check periodically whether user has already authorized a consent
        sleep_time = 3
        for _ in range(3):
            try:
                make_token_response = auth_api.make_token(
                    "authorization_code",  # grant type, MUST be set to "authorization_code"
                    code="",
                    auth_env=auth_response.env,
                )
            except enablebanking.MakeTokenException as e:
                logging.debug(
                    f"Failed to get authorization code, sleeping for {sleep_time} seconds"
                )
                time.sleep(sleep_time)
            else:
                break

    logging.info("Token: %s", make_token_response)

    aisp_api = enablebanking.AISPApi(
        api_client
    )  # api_client has already accessToken and refreshToken applied after call to makeToken()

    if api_meta.modify_consents_info[0].info.before_accounts:
        # bank requires to create a consent explicitly before accessing list of accounts
        consent = aisp_api.modify_consents(access=access)
        logging.debug(f"Consent: {consent}")
        try:
            # If returned consent has a redirect url, we need to redirect a PSU there
            consent_url = consent.links.redirect.href
            redirect_url = read_redirected_url(consent_url, REDIRECT_URL)
            logging.debug(f"Redirect url: {redirect_url}")
        except AttributeError:
            pass

    accounts = aisp_api.get_accounts()
    logging.info("Accounts info: %s", accounts)

    if api_meta.modify_consents_info[0].info.accounts_required:
        # bank requires to create a consent with account ids specified
        account_ids = [
            enablebanking.AccountIdentification(iban=acc.account_id.iban)
            for acc in accounts.accounts
        ]
        access.accounts = account_ids
        consent = aisp_api.modify_consents(access=access)
        logging.debug(f"Consent: {consent}")
        try:
            # If returned consent has a redirect url, we need to redirect a PSU there
            consent_url = consent.links.redirect.href
            redirect_url = read_redirected_url(consent_url, REDIRECT_URL)
            logging.debug(f"Redirect url: {redirect_url}")
        except AttributeError:
            pass

    for account in accounts.accounts:
        transactions = aisp_api.get_account_transactions(account.resource_id)
        logging.info("Transactions info: %s", transactions)

        balances = aisp_api.get_account_balances(account.resource_id)
        logging.info("Balances info: %s", balances)


if __name__ == "__main__":
    main()
```

**Comment by botsman** [comment]
I assume this is solved or not needed anymore.
If not, feel free to reopen
